import "dotenv/config";

export const env = {
  MYSQL_ROOT_PASSWORD: process.env.MYSQL_ROOT_PASSWORD,
  MYSQL_DATABASE: process.env.MYSQL_DATABASE,
  MYSQL_USER: process.env.MYSQL_USER,
  MYSQL_PASSWORD: process.env.MYSQL_PASSWORD,

  WEBSITE_DOMAIN_DEVELOPMENT: process.env.WEBSITE_DOMAIN_DEVELOPMENT,
  WEBSITE_DOMAIN_PRODUCTION: process.env.WEBSITE_DOMAIN_PRODUCTION,

  APP_HOST: process.env.APP_HOST,
  APP_PORT: process.env.APP_PORT,

  CLIENT_URL: process.env.CLIENT_URL,

  BUILD_MODE: process.env.BUILD_MODE,

  DATABASE_URL: process.env.DATABASE_URL,
  DATABASE_URL_MIGRATE: process.env.DATABASE_URL_MIGRATE,
  DATABASE_USER: process.env.DATABASE_USER,
  DATABASE_PASSWORD: process.env.DATABASE_PASSWORD,
  DATABASE_NAME: process.env.DATABASE_NAME,
  DATABASE_HOST: process.env.DATABASE_HOST,
  DATABASE_PORT: process.env.DATABASE_PORT,

  GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET,
  GOOGLE_REDIRECT_URL: process.env.GOOGLE_REDIRECT_URL,

  PORT: process.env.PORT,

  BREVO_API_KEY: process.env.BREVO_API_KEY,
  ADMIN_EMAIL_ADDRESS: process.env.ADMIN_EMAIL_ADDRESS,
  ADMIN_EMAIL_NAME: process.env.ADMIN_EMAIL_NAME,

  RESEND_API_KEY: process.env.RESEND_API_KEY,
  RESEND_ADMIN_SENDER_EMAIL: process.env.RESEND_ADMIN_SENDER_EMAIL,

  MAILERSEND_API_KEY: process.env.MAILERSEND_API_KEY,

  CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,

  PAYOS_CLIENT_ID: process.env.PAYOS_CLIENT_ID,
  PAYOS_API_KEY: process.env.PAYOS_API_KEY,
  PAYOS_CHECKSUM_KEY: process.env.PAYOS_CHECKSUM_KEY,
  PAYOS_RETURN_URL: process.env.PAYOS_RETURN_URL,
  PAYOS_CANCEL_URL: process.env.PAYOS_CANCEL_URL,
  PAYOS_WEBHOOK_URL: process.env.PAYOS_WEBHOOK_URL,

  GEMINI_API_KEY: process.env.GEMINI_API_KEY,
  GEMINI_KEY: process.env.GEMINI_KEY,
  GEMINI_BASE_URL: process.env.GEMINI_BASE_URL,
  GEMINI_CHAT_COMPLETIONS_PATH: process.env.GEMINI_CHAT_COMPLETIONS_PATH,
  GEMINI_CHAT_MODEL: process.env.GEMINI_CHAT_MODEL,
  GEMINI_EMBEDDINGS_PATH: process.env.GEMINI_EMBEDDINGS_PATH,
  GEMINI_EMBEDDING_MODEL: process.env.GEMINI_EMBEDDING_MODEL,
  GEMINI_EMBEDDING_DIMENSIONS: process.env.GEMINI_EMBEDDING_DIMENSIONS,

  QDRANT_HOST: process.env.QDRANT_HOST,
  QDRANT_PORT: process.env.QDRANT_PORT,
  QDRANT_USE_TLS: process.env.QDRANT_USE_TLS,
  QDRANT_INITIALIZE_SCHEMA: process.env.QDRANT_INITIALIZE_SCHEMA,
  QDRANT_API_KEY: process.env.QDRANT_API_KEY,
  QDRANT_COLLECTION_NAME: process.env.QDRANT_COLLECTION_NAME,

  REDIS_HOST: process.env.REDIS_HOST,
  REDIS_PORT: process.env.REDIS_PORT,
  CHATBOT_MEMORY_TTL_SECONDS: process.env.CHATBOT_MEMORY_TTL_SECONDS,
};
